/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotasFiscaisRouteImport } from './routes/notas-fiscais'
import { Route as InteligenciaIbsCbsRouteImport } from './routes/inteligencia-ibs-cbs'
import { Route as FluxoDeCaixaRouteImport } from './routes/fluxo-de-caixa'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CentralDeAcoesRouteImport } from './routes/central-de-acoes'
import { Route as IndexRouteImport } from './routes/index'

const NotasFiscaisRoute = NotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaIbsCbsRoute = InteligenciaIbsCbsRouteImport.update({
  id: '/inteligencia-ibs-cbs',
  path: '/inteligencia-ibs-cbs',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoDeCaixaRoute = FluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeAcoesRoute = CentralDeAcoesRouteImport.update({
  id: '/central-de-acoes',
  path: '/central-de-acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central-de-acoes': typeof CentralDeAcoesRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/inteligencia-ibs-cbs': typeof InteligenciaIbsCbsRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/central-de-acoes': typeof CentralDeAcoesRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/inteligencia-ibs-cbs': typeof InteligenciaIbsCbsRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/central-de-acoes': typeof CentralDeAcoesRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/inteligencia-ibs-cbs': typeof InteligenciaIbsCbsRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/central-de-acoes'
    | '/compliance'
    | '/fluxo-de-caixa'
    | '/inteligencia-ibs-cbs'
    | '/notas-fiscais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/central-de-acoes'
    | '/compliance'
    | '/fluxo-de-caixa'
    | '/inteligencia-ibs-cbs'
    | '/notas-fiscais'
  id:
    | '__root__'
    | '/'
    | '/central-de-acoes'
    | '/compliance'
    | '/fluxo-de-caixa'
    | '/inteligencia-ibs-cbs'
    | '/notas-fiscais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralDeAcoesRoute: typeof CentralDeAcoesRoute
  ComplianceRoute: typeof ComplianceRoute
  FluxoDeCaixaRoute: typeof FluxoDeCaixaRoute
  InteligenciaIbsCbsRoute: typeof InteligenciaIbsCbsRoute
  NotasFiscaisRoute: typeof NotasFiscaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notas-fiscais': {
      id: '/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof NotasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-ibs-cbs': {
      id: '/inteligencia-ibs-cbs'
      path: '/inteligencia-ibs-cbs'
      fullPath: '/inteligencia-ibs-cbs'
      preLoaderRoute: typeof InteligenciaIbsCbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-de-caixa': {
      id: '/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof FluxoDeCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-acoes': {
      id: '/central-de-acoes'
      path: '/central-de-acoes'
      fullPath: '/central-de-acoes'
      preLoaderRoute: typeof CentralDeAcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralDeAcoesRoute: CentralDeAcoesRoute,
  ComplianceRoute: ComplianceRoute,
  FluxoDeCaixaRoute: FluxoDeCaixaRoute,
  InteligenciaIbsCbsRoute: InteligenciaIbsCbsRoute,
  NotasFiscaisRoute: NotasFiscaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
