/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotasFiscaisRouteImport } from './routes/notas-fiscais'
import { Route as FluxoDeCaixaRouteImport } from './routes/fluxo-de-caixa'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'

const NotasFiscaisRoute = NotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoDeCaixaRoute = FluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compliance' | '/fluxo-de-caixa' | '/notas-fiscais'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compliance' | '/fluxo-de-caixa' | '/notas-fiscais'
  id: '__root__' | '/' | '/compliance' | '/fluxo-de-caixa' | '/notas-fiscais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  FluxoDeCaixaRoute: typeof FluxoDeCaixaRoute
  NotasFiscaisRoute: typeof NotasFiscaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notas-fiscais': {
      id: '/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof NotasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-de-caixa': {
      id: '/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof FluxoDeCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  FluxoDeCaixaRoute: FluxoDeCaixaRoute,
  NotasFiscaisRoute: NotasFiscaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
