/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitacoesDocsRouteImport } from './routes/solicitacoes-docs'
import { Route as PainelContadorRouteImport } from './routes/painel-contador'
import { Route as NotasFiscaisRouteImport } from './routes/notas-fiscais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteligenciaIbsCbsRouteImport } from './routes/inteligencia-ibs-cbs'
import { Route as GestaoGuiasRouteImport } from './routes/gestao-guias'
import { Route as FluxoDeCaixaRouteImport } from './routes/fluxo-de-caixa'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CentralDoContadorRouteImport } from './routes/central-do-contador'
import { Route as CentralDeAcoesRouteImport } from './routes/central-de-acoes'
import { Route as IndexRouteImport } from './routes/index'

const SolicitacoesDocsRoute = SolicitacoesDocsRouteImport.update({
  id: '/solicitacoes-docs',
  path: '/solicitacoes-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelContadorRoute = PainelContadorRouteImport.update({
  id: '/painel-contador',
  path: '/painel-contador',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasFiscaisRoute = NotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaIbsCbsRoute = InteligenciaIbsCbsRouteImport.update({
  id: '/inteligencia-ibs-cbs',
  path: '/inteligencia-ibs-cbs',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoGuiasRoute = GestaoGuiasRouteImport.update({
  id: '/gestao-guias',
  path: '/gestao-guias',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoDeCaixaRoute = FluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDoContadorRoute = CentralDoContadorRouteImport.update({
  id: '/central-do-contador',
  path: '/central-do-contador',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeAcoesRoute = CentralDeAcoesRouteImport.update({
  id: '/central-de-acoes',
  path: '/central-de-acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central-de-acoes': typeof CentralDeAcoesRoute
  '/central-do-contador': typeof CentralDoContadorRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/gestao-guias': typeof GestaoGuiasRoute
  '/inteligencia-ibs-cbs': typeof InteligenciaIbsCbsRoute
  '/login': typeof LoginRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
  '/painel-contador': typeof PainelContadorRoute
  '/solicitacoes-docs': typeof SolicitacoesDocsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/central-de-acoes': typeof CentralDeAcoesRoute
  '/central-do-contador': typeof CentralDoContadorRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/gestao-guias': typeof GestaoGuiasRoute
  '/inteligencia-ibs-cbs': typeof InteligenciaIbsCbsRoute
  '/login': typeof LoginRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
  '/painel-contador': typeof PainelContadorRoute
  '/solicitacoes-docs': typeof SolicitacoesDocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/central-de-acoes': typeof CentralDeAcoesRoute
  '/central-do-contador': typeof CentralDoContadorRoute
  '/compliance': typeof ComplianceRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/gestao-guias': typeof GestaoGuiasRoute
  '/inteligencia-ibs-cbs': typeof InteligenciaIbsCbsRoute
  '/login': typeof LoginRoute
  '/notas-fiscais': typeof NotasFiscaisRoute
  '/painel-contador': typeof PainelContadorRoute
  '/solicitacoes-docs': typeof SolicitacoesDocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/central-de-acoes'
    | '/central-do-contador'
    | '/compliance'
    | '/fluxo-de-caixa'
    | '/gestao-guias'
    | '/inteligencia-ibs-cbs'
    | '/login'
    | '/notas-fiscais'
    | '/painel-contador'
    | '/solicitacoes-docs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/central-de-acoes'
    | '/central-do-contador'
    | '/compliance'
    | '/fluxo-de-caixa'
    | '/gestao-guias'
    | '/inteligencia-ibs-cbs'
    | '/login'
    | '/notas-fiscais'
    | '/painel-contador'
    | '/solicitacoes-docs'
  id:
    | '__root__'
    | '/'
    | '/central-de-acoes'
    | '/central-do-contador'
    | '/compliance'
    | '/fluxo-de-caixa'
    | '/gestao-guias'
    | '/inteligencia-ibs-cbs'
    | '/login'
    | '/notas-fiscais'
    | '/painel-contador'
    | '/solicitacoes-docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralDeAcoesRoute: typeof CentralDeAcoesRoute
  CentralDoContadorRoute: typeof CentralDoContadorRoute
  ComplianceRoute: typeof ComplianceRoute
  FluxoDeCaixaRoute: typeof FluxoDeCaixaRoute
  GestaoGuiasRoute: typeof GestaoGuiasRoute
  InteligenciaIbsCbsRoute: typeof InteligenciaIbsCbsRoute
  LoginRoute: typeof LoginRoute
  NotasFiscaisRoute: typeof NotasFiscaisRoute
  PainelContadorRoute: typeof PainelContadorRoute
  SolicitacoesDocsRoute: typeof SolicitacoesDocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitacoes-docs': {
      id: '/solicitacoes-docs'
      path: '/solicitacoes-docs'
      fullPath: '/solicitacoes-docs'
      preLoaderRoute: typeof SolicitacoesDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-contador': {
      id: '/painel-contador'
      path: '/painel-contador'
      fullPath: '/painel-contador'
      preLoaderRoute: typeof PainelContadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas-fiscais': {
      id: '/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof NotasFiscaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-ibs-cbs': {
      id: '/inteligencia-ibs-cbs'
      path: '/inteligencia-ibs-cbs'
      fullPath: '/inteligencia-ibs-cbs'
      preLoaderRoute: typeof InteligenciaIbsCbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-guias': {
      id: '/gestao-guias'
      path: '/gestao-guias'
      fullPath: '/gestao-guias'
      preLoaderRoute: typeof GestaoGuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-de-caixa': {
      id: '/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof FluxoDeCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-do-contador': {
      id: '/central-do-contador'
      path: '/central-do-contador'
      fullPath: '/central-do-contador'
      preLoaderRoute: typeof CentralDoContadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-acoes': {
      id: '/central-de-acoes'
      path: '/central-de-acoes'
      fullPath: '/central-de-acoes'
      preLoaderRoute: typeof CentralDeAcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralDeAcoesRoute: CentralDeAcoesRoute,
  CentralDoContadorRoute: CentralDoContadorRoute,
  ComplianceRoute: ComplianceRoute,
  FluxoDeCaixaRoute: FluxoDeCaixaRoute,
  GestaoGuiasRoute: GestaoGuiasRoute,
  InteligenciaIbsCbsRoute: InteligenciaIbsCbsRoute,
  LoginRoute: LoginRoute,
  NotasFiscaisRoute: NotasFiscaisRoute,
  PainelContadorRoute: PainelContadorRoute,
  SolicitacoesDocsRoute: SolicitacoesDocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
